name: KiiLibHttpClient
description: HTTP client for KiiLib

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: "0.12.0+2"
  kiilib_core: "0.0.1+1"

dev_dependencies:
  test: "^1.5.1"
